# Generated by Django 5.1.4 on 2024-12-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrecord',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
